//Для наполнения карточки товара
export const FETCH_PRODUCT_CARD_REQUEST = "FETCH_PRODUCT_CARD_REQUEST";
export const FETCH_PRODUCT_CARD_FAILURE = "FETCH_PRODUCT_CARD_FAILURE";
export const FETCH_PRODUCT_CARD_SUCCESS = "FETCH_PRODUCT_CARD_SUCCESS";
