image: Visual Studio 2015

branches:
  only:
    - master

cache: node_modules

init:
  - ps: Install-Product node 10

install:
  - yarn

build: off

build_script:
  - yarn run build

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo https://%GITHUB_TOKEN%:x-oauth-basic@github.com>%USERPROFILE%\.git-credentials
  - dos2unix %USERPROFILE%\.git-credentials
  - npx push-dir --dir=build --branch=gh-pages --force --verbose
