export const FETCH_SALES_HITS_REQUEST = "FETCH_SALES_HITS_REQUEST";
export const FETCH_SALES_HITS_FAILURE = "FETCH_SALES_HITS_FAILURE";
export const FETCH_SALES_HITS_SUCCESS = "FETCH_SALES_HITS_SUCCESS";
