//Для блока "Каталог" на страницах "/" и "/catalog.html"
export const FETCH_PRODUCTS_LIST_REQUEST = "FETCH_PRODUCTS_LIST_REQUEST";
export const FETCH_PRODUCTS_LIST_FAILURE = "FETCH_PRODUCTS_LIST_FAILURE";
export const FETCH_PRODUCTS_LIST_SUCCESS = "FETCH_PRODUCTS_LIST_SUCCESS";

//Для фильтра блока "Каталог" на страницах "/" и "/catalog.html"
export const FETCH_PRODUCTS_LIST_FILTER_REQUEST =
  "FETCH_PRODUCTS_LIST_FILTER_REQUEST";
export const FETCH_PRODUCTS_LIST_FILTER_FAILURE =
  "FETCH_PRODUCTS_LIST_FILTER_FAILURE";
export const FETCH_PRODUCTS_LIST_FILTER_SUCCESS =
  "FETCH_PRODUCTS_LIST_FILTER_SUCCESS";

//Для кнопки "Загрузить еще" (для отдельных категорий) на страницах "/" и "/catalog.html"
export const FETCH_DOWNLOAD_MORE_REQUEST = "FETCH_DOWNLOAD_MORE_REQUEST";
export const FETCH_DOWNLOAD_MORE_FAILURE = "FETCH_DOWNLOAD_MORE_FAILURE";
export const FETCH_DOWNLOAD_MORE_SUCCESS = "FETCH_DOWNLOAD_MORE_SUCCESS";

//Для кнопки "Загрузить еще" (для всех категорий) на страницах "/" и "/catalog.html"
export const FETCH_DOWNLOAD_MORE_ALL_REQUEST =
  "FETCH_DOWNLOAD_MORE_ALL_REQUEST";
export const FETCH_DOWNLOAD_MORE_ALL_FAILURE =
  "FETCH_DOWNLOAD_MORE_ALL_FAILURE";
export const FETCH_DOWNLOAD_MORE_ALL_SUCCESS =
  "FETCH_DOWNLOAD_MORE_ALL_SUCCESS";

//Для работы поиска
export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

//Для загрузки каталога при заполненном поиске в хедере сайта
export const FETCH_SEARCH_PRODUCTS_LIST_REQUEST =
  "FETCH_SEARCH_PRODUCTS_LIST_REQUEST";
export const FETCH_SEARCH_PRODUCTS_LIST_FAILURE =
  "FETCH_SEARCH_PRODUCTS_LIST_FAILURE";
export const FETCH_SEARCH_PRODUCTS_LIST_SUCCESS =
  "FETCH_SEARCH_PRODUCTS_LIST_SUCCESS";

//Для фильтра блока "Каталог" на странице "/catalog.html" с результатами поиска
export const FETCH_SEARCH_PRODUCTS_LIST_FILTER_REQUEST =
  "FETCH_SEARCH_PRODUCTS_LIST_FILTER_REQUEST";
export const FETCH_SEARCH_PRODUCTS_LIST_FILTER_FAILURE =
  "FETCH_SEARCH_PRODUCTS_LIST_FILTER_FAILURE";
export const FETCH_SEARCH_PRODUCTS_LIST_FILTER_SUCCESS =
  "FETCH_SEARCH_PRODUCTS_LIST_FILTER_SUCCESS";

//Для вкладки "Все" фильтра блока "Каталог" на странице "/catalog.html" с результатами поиска
export const FETCH_ALL_SEARCH_PRODUCTS_LIST_FILTER_REQUEST =
  "FETCH_ALL_SEARCH_PRODUCTS_LIST_FILTER_REQUEST";
export const FETCH_ALL_SEARCH_PRODUCTS_LIST_FILTER_FAILURE =
  "FETCH_ALL_SEARCH_PRODUCTS_LIST_FILTER_FAILURE";
export const FETCH_ALL_SEARCH_PRODUCTS_LIST_FILTER_SUCCESS =
  "FETCH_ALL_SEARCH_PRODUCTS_LIST_FILTER_SUCCESS";

//Для кнопки "Загрузить еще" (для отдельных категорий) на странице "/catalog.html" для результатов поиска
export const FETCH_DOWNLOAD_MORE_SEARCH_RESULTS_REQUEST =
  "FETCH_DOWNLOAD_MORE_SEARCH_RESULTS_REQUEST";
export const FETCH_DOWNLOAD_MORE_SEARCH_RESULTS_FAILURE =
  "FETCH_DOWNLOAD_MORE_SEARCH_RESULTS_FAILURE";
export const FETCH_DOWNLOAD_MORE_SEARCH_RESULTS_SUCCESS =
  "FETCH_DOWNLOAD_MORE_SEARCH_RESULTS_SUCCESS";

//Для кнопки "Загрузить еще" (для всех категорий) на странице "/catalog.html" для результатов поиска
export const FETCH_ALL_DOWNLOAD_MORE_SEARCH_RESULTS_REQUEST =
  "FETCH_ALL_DOWNLOAD_MORE_SEARCH_RESULTS_REQUEST";
export const FETCH_ALL_DOWNLOAD_MORE_SEARCH_RESULTS_FAILURE =
  "FETCH_ALL_DOWNLOAD_MORE_SEARCH_RESULTS_FAILURE";
export const FETCH_ALL_DOWNLOAD_MORE_SEARCH_RESULTS_SUCCESS =
  "FETCH_ALL_DOWNLOAD_MORE_SEARCH_RESULTS_SUCCESS";
