//Для отображения товаров в корзине
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCTS_IN_CART = "ADD_PRODUCTS_IN_CART";
export const REMOVE_PRODUCT_IN_CART = "REMOVE_PRODUCT_IN_CART";
export const DELETE_PRODUCTS_FROM_CART_AFTER_ORDER =
  "DELETE_PRODUCTS_FROM_CART_AFTER_ORDER";
